version: '3.8'

services:
  server:
    environment:
      - APP_ENV=local
    container_name: conexa-back-end
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: base
    ports:
      - 4002:4002
    env_file:
       - ./src/src/.env.local
    depends_on:
      - conexa_db
    command: >
      sh -c "npm run start:dev"
    volumes:
      - ./src/src:/app/src

  conexa_db:
    hostname: conexa_db
    container_name: conexa_db
    image: mariadb:11.2.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conexa
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3317:3306
    volumes:
      - ./dbdata:/var/lib/mysql

volumes:
  mariadb_data: