name: Deploy Dockerized NestJS to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2 and run Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.EC2_PATH }}
            git pull origin main
            docker build -t nest-app .
            docker stop nest-app || true
            docker rm nest-app || true
            docker run -d --name nest-app -p 3000:3000 nest-app
